[build]
builder = "DOCKERFILE"
dockerfilePath = "dockerfile/Dockerfile"

[deploy]
startCommand = "cd app && python -m uvicorn main:app --host 0.0.0.0 --port \$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"